# configs/run_A.yaml

# General experiment settings
runs: 5
output_dir: "./results/"
game: "solid"
algorithm: "PPO"
policy: "MlpPolicy"
conda_env: "affect-envs"

# Hardware settings
use_gpu: 0
headless: 1

# Specific game and agent parameters for this run
weight: 1
cluster: 0
target_arousal: 0
classifier: 0
preference: 1

# Specific algorithm parameters
periodic_ra: 0
cv: 0
grayscale: 0
discretize: 0
